[package]
name = "clipboard"
version = "0.1.0"
edition = "2021"

[dependencies]
clipboard-rs = "0.1.6"
serde = { version = "1.*", features = ["derive"] } 
serde_json = "1.*"
chrome_native_messaging = "0.3.0"